---
- hosts: webservers 
  become: True
  tasks:
    - name: Deploy static website
      copy:
        src: /var/lib/jenkins/workspace/CA-ANSIBLE/target/customer-data-0.0.1-SNAPSHOT.war
        dest: /var/lib/tomcat9/webapps
...
